apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nextjs-app
  labels:
    app: my-nextjs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nextjs-app
  template:
    metadata:
      labels:
        app: my-nextjs-app
    spec:
      containers:
        - name: my-nextjs-container
          image: ghcr.io/<YOUR_GITHUB_USERNAME>/my-nextjs-app:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
