apiVersion: v1
kind: Service
metadata:
  name: my-nextjs-service
spec:
  selector:
    app: my-nextjs-app
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
